version: '3'

volumes:
  cride_local_postgres_data: {}
  cride_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: cride_local_django
    container_name: cride_local_django
    depends_on:
      - postgres      
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: cride_production_postgres
    container_name: cride_local_postgres
    volumes:
      - cride_local_postgres_data:/var/lib/postgresql/data
      - cride_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres